[project]
name = "frequency-analysis"
version = "0.1.0"
description = "Frequency Analysis of Neural Networks"
authors = ["Mithilesh R"]
channels = ["conda-forge", "pytorch", "nvidia"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.9,<3.13"
numpy = "*"
matplotlib = "*"
pillow = "*"
tqdm = "*"
timm = "*"
datasets = "*"
huggingface_hub = "*"
jupyter = "*"
ipykernel = "*"
pip = "*"

[tasks]
install-torch-cuda = "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118"
install-torch-cpu = "pip install torch torchvision torchaudio"
notebook = "jupyter notebook FrequencyAnalysis.ipynb"
lab = "jupyter lab"
check-gpu = "python check_gpu.py"

[environments]
default = {solve-group = "default"}
